### ISSUE TITLE
How do I request the server to delete data when deleting the side image?

### ISSUE THREAD

**Issue by yinmingming** [redgoose-dev/photo-layout-editor#44]

**Comment by redgoose-dev** [comment]
@yinmingming 

Sorry to reply late.
The callback function of the point where the image is deleted must be created anew.

Please wait for refactoring.

**Comment by yinmingming** [comment]
@redgoose-dev  Ok thank you for your reply.

**Comment by redgoose-dev** [comment]
Forgive me for being late.
Finally you can use the callback function.

See the following links.
- https://github.com/redgoose-dev/photo-layout-editor/blob/master/app.js
- https://github.com/redgoose-dev/react-photo-layout-editor#callback

**Comment by yinmingming** [comment]
@redgoose-dev cool!  thank you very much!
